### ISSUE TITLE
i receive empty string with readExcel

### ISSUE THREAD

**Issue by AskMeCode** [seccoding/Excel#1]
Hello Dear than you for your sharing
Can you please help me i have problem with your class ExcelRead i receive nothing
  public String ExcelReadcol(String columnName,String filePath,int startRow)
  {
		ReadOption ro = new ReadOption();
		ro.setFilePath(filePath);
		ro.setOutputColumns("A","B","C","D","E","F","G","H");
		ro.setStartRow(startRow);
		List<Map<String, String>> result = ExcelRead.read(ro);
		 String test = "";
		for (Map<String, String> map : result) {
			//System.out.println(map.get("E"));
			if(map.get(columnName) != "")
				test = test+map.get(columnName);
		}

	return test;
  }

**Comment by seccoding** [comment]
> if(map.get(columnName) != "")
&nbsp;&nbsp;&nbsp;test = test+map.get(columnName);
}

Please convert the above code into the following code.

> if ( map.get(columnName) != null && !map.get(columnName).equals("") ) {
&nbsp;&nbsp;&nbsp;test = test+map.get(columnName);
}
